# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-27 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('class', 'Classified'), ('public', 'Public'), ('dec', 'Declassified'), ('secret', 'Calendestine')], max_length=10)),
                ('Code', models.CharField(max_length=20, null=True)),
                ('Index', models.TextField(max_length=700, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operation_Name', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='documents',
            name='Operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doc_viewer.Operations'),
        ),
    ]
