# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-17 12:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doc_viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_rank', models.CharField(choices=[('High', 'High Privileged'), ('Normal', 'Non-Privileged')], max_length=10)),
                ('active_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doc_viewer.Operations')),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
