# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-17 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_viewer', '0003_auto_20181217_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='Category',
            field=models.CharField(choices=[('Classified', 'Classified'), ('Public', 'Public'), ('Declassified', 'Declassified'), ('Calendestine', 'Calendestine')], max_length=15),
        ),
    ]
